import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bem-vindo ao  <a href="https://instagram.com/projetoceos">Projeto Céos!</a>
        </h1>

        <p className={styles.description}>
          Projeto do João e da Ketlyn {' '}
          <code className={styles.code}>dev</code>
        </p>

        <div className={styles.grid}>
          <Link href="https://garrulous-hero-1f4.notion.site/Projeto-C-os-Dev-Aprendiz-265d9164a0704b85a365b8826ac56116">
            <a className={styles.card}>
              <h2>Documentação &rarr;</h2>
              <p>Base de conhecimento do projeto</p>
            </a>
          </Link>

          <Link href="/reviews"> 
          <a className={styles.card}>
            <h2>Avaliações &rarr;</h2>
            <p>Um CRUD de avaliações!</p>
          </a>
          </Link>

         <Link href="/blog">
          <a
            className={styles.card}
          >
            <h2>Blog &rarr;</h2>
            <p>Um exemplo de blog.</p>
          </a>
          </Link>

          <Link href="/sobre">
          <a
            className={styles.card}
          >
            <h2>Sobre &rarr;</h2>
            <p>
              Um exemplo de página sobre.
            </p>
          </a>
          </Link>  
        </div>
      </main>
      

      <footer className={styles.footer}>
    
      <Link href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
        <a
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>
          </span>
        </a>
        </Link>
      </footer>
    </div>
  );
}